(menu-bar-mode -1)
(toggle-scroll-bar -1)
(tool-bar-mode -1)
;(add-to-list 'default-frame-alist '(fullscreen . maximized))
(global-linum-mode 1)
(add-to-list 'default-frame-alist '(font . "Consolas" ))
(set-face-attribute 'default t :font "Consolas" )
(set-face-attribute 'default nil :height 110)
(fill-column-indicator 80)
